name: Freqtrade Data Download

on:
  workflow_dispatch:  # لتشغيله يدويًا من GitHub Actions

jobs:
  download_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libta-lib0 libta-lib0-dev wget

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install freqtrade[full]
          pip install ta-lib-binary  # بايندنج جاهز لـ TA-Lib لتجنب مشاكل البناء

      - name: Download Binance Data
        run: |
          freqtrade download-data \
            --timeframes 15m \
            --exchange binance \
            --pairs ETH/USDT ETH/BTC XRP/USDT BTC/USDT XRP/ETH \
            --prepend \
            --timerange 20210101-20250101
